In [5]:
import numpy as np
def mymat(l):
    print("Input Vector:",l)
    noc=3
    l1=np.array([l])
    l2=l1.size
    print("Input Vector Size:",l2)
    bool=False
    l3=np.column_stack([x**(noc-1-i) for x in l1 for i in range(noc) if bool==False]).reshape(l2,noc)
    print("Output Matrix:\n\n",l3,"\n")
    return l3   

In [6]:
l2=[1,2,3,4]
mymat(l2)

Input Vector: [1, 2, 3, 4]
Input Vector Size: 4
Output Matrix:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]] 



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
np.vander(x,N, increasing = True)
np.column_stack([x**(N-i-1) for i in range(N)])

In [2]:
l2=[1,2,3,4]
mymat(l2)

Input Vector: [1, 2, 3, 4]
4
Output Matrix:

 [[ 1  4  9]
 [16  1  2]
 [ 3  4  1]
 [ 1  1  1]] 



array([[ 1,  4,  9],
       [16,  1,  2],
       [ 3,  4,  1],
       [ 1,  1,  1]], dtype=int32)