In [5]:
import sys
print(sys.path)

['C:\\Users\\Sreenivasan', 'C:\\Users\\Sreenivasan\\Anaconda3\\python37.zip', 'C:\\Users\\Sreenivasan\\Anaconda3\\DLLs', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib', 'C:\\Users\\Sreenivasan\\Anaconda3', '', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib\\site-packages', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Sreenivasan\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Sreenivasan\\.ipython']


In [7]:
import pandas as pd
import numpy as np
import csv
a=open('hrdata.csv')
a

<_io.TextIOWrapper name='hrdata.csv' mode='r' encoding='cp1252'>

In [8]:
a1=csv.reader(a)
for i in a1:
    print(i)

['Name', 'Hire Date', 'Salary', 'Sick Days remaining']
['Fred', '10/10/10', '10000', '10']


In [10]:
with open('hrdata.csv') as f:
    lines=list(csv.reader(f))
lines

[['Name', 'Hire Date', 'Salary', 'Sick Days remaining'],
 ['Fred', '10/10/10', '10000', '10']]

In [18]:
a=[1,2]
b=[3,4]
list(zip(a,b))

[(1, 3), (2, 4)]

In [31]:
line=['a,b,c','1,2,3','2,3,4']
line

['a,b,c', '1,2,3', '2,3,4']

In [32]:
k, v= line[0],line[1:]
v

['1,2,3', '2,3,4']

In [25]:
list(zip(*v))

[('1', '2'), ('2', '3'), ('3', '4')]

In [36]:
list(zip(k,zip(*v)))

[('a', ('1', '2')),
 (',', (',', ',')),
 ('b', ('2', '3')),
 (',', (',', ',')),
 ('c', ('3', '4'))]

In [37]:
list(zip(k,v))

[('a', '1,2,3'), (',', '2,3,4')]

In [41]:
{k:v for k,v in (zip(k,v))}

{'a': '1,2,3', ',': '2,3,4'}

In [63]:
import json
obj="""
{"name":"wes",
"places":["a","b","c"],
"none":"Null",
"sib":[{"name":["a","b","c"]},
       {"name1":["1","2","3"]}] 
}
"""

In [64]:
j=json.loads(obj)

In [66]:
j['sib']

[{'name': ['a', 'b', 'c']}, {'name1': ['1', '2', '3']}]

In [72]:
d=pd.DataFrame(j['sib'],columns=['name','name1','name2'])

In [73]:
d

name      name1  name2
0  [a, b, c]        NaN    NaN
1        NaN  [1, 2, 3]    NaN

In [74]:
d.to_json("d.json",orient='records')

In [75]:
import requests

In [79]:
url='https://api.github.com/repos/pandas-dev/pandas/issues'
r=requests.get(url)

In [80]:
type(r)

requests.models.Response

In [83]:
u=r.json()

In [87]:
u[0]['user']['url']

'https://api.github.com/users/jolespin'

In [88]:
u

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/34320',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/34320/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/34320/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/34320/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/34320',
  'id': 623395066,
  'node_id': 'MDU6SXNzdWU2MjMzOTUwNjY=',
  'number': 34320,
  'title': 'ENH: `name` attribute for pd.Interval',
  'user': {'login': 'jolespin',
   'id': 9061708,
   'node_id': 'MDQ6VXNlcjkwNjE3MDg=',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/9061708?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jolespin',
   'html_url': 'https://github.com/jolespin',
   'followers_url': 'https://api.github.com/users/jolespin/followers',
   'following_url': 'https://api.github.

In [89]:
v=pd.DataFrame(u)
v

url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pandas-dev/pandas...   
10  https://api.github.com/repos/pandas-dev/pandas...   
11  https://api.github.com/repos/pandas-dev/pandas...   
12  https://api.github.com/repos/pandas-dev/pandas...   
13  https://api.github.com/repos/pandas-dev/pandas...   
14  https://api.github.com/repos/pandas-dev/pandas...   
15  https://api.github.com/repos/pandas-dev/pandas...   
16  https://api.github.com/repos/pandas-dev/pandas...   
17  https://api.github.com/repos/pandas-dev/pandas...   
18  https://api.github.com/repos/pandas-dev/pandas...   
19  https://api.github.com/repos/pandas-dev/pandas...   
20  https://api.github.com/repos/pandas-dev/pandas...   
21  https://api.github.com/repos/pandas-dev/pandas...   
22  https://api.github.com/repos/pandas-dev/pandas...   
23  https://api.github.com/repos/pandas-dev/pandas...   
24  https://api.github.com/repos/pandas-dev/pandas...   
25  https://api.github.com/repos/pandas-dev/pandas...   
26  https://api.github.com/repos/pandas-dev/pandas...   
27  https://api.github.com/repos/pandas-dev/pandas...   
28  https://api.github.com/repos/pandas-dev/pandas...   
29  https://api.github.com/repos/pandas-dev/pandas...   

                                    repository_url  \
0   https://api.github.com/repos/pandas-dev/pandas   
1   https://api.github.com/repos/pandas-dev/pandas   
2   https://api.github.com/repos/pandas-dev/pandas   
3   https://api.github.com/repos/pandas-dev/pandas   
4   https://api.github.com/repos/pandas-dev/pandas   
5   https://api.github.com/repos/pandas-dev/pandas   
6   https://api.github.com/repos/pandas-dev/pandas   
7   https://api.github.com/repos/pandas-dev/pandas   
8   https://api.github.com/repos/pandas-dev/pandas   
9   https://api.github.com/repos/pandas-dev/pandas   
10  https://api.github.com/repos/pandas-dev/pandas   
11  https://api.github.com/repos/pandas-dev/pandas   
12  https://api.github.com/repos/pandas-dev/pandas   
13  https://api.github.com/repos/pandas-dev/pandas   
14  https://api.github.com/repos/pandas-dev/pandas   
15  https://api.github.com/repos/pandas-dev/pandas   
16  https://api.github.com/repos/pandas-dev/pandas   
17  https://api.github.com/repos/pandas-dev/pandas   
18  https://api.github.com/repos/pandas-dev/pandas   
19  https://api.github.com/repos/pandas-dev/pandas   
20  https://api.github.com/repos/pandas-dev/pandas   
21  https://api.github.com/repos/pandas-dev/pandas   
22  https://api.github.com/repos/pandas-dev/pandas   
23  https://api.github.com/repos/pandas-dev/pandas   
24  https://api.github.com/repos/pandas-dev/pandas   
25  https://api.github.com/repos/pandas-dev/pandas   
26  https://api.github.com/repos/pandas-dev/pandas   
27  https://api.github.com/repos/pandas-dev/pandas   
28  https://api.github.com/repos/pandas-dev/pandas   
29  https://api.github.com/repos/pandas-dev/pandas   

                                           labels_url  \
0   https://api.github.com/repos/pandas-dev/pandas...   
1   https://api.github.com/repos/pandas-dev/pandas...   
2   https://api.github.com/repos/pandas-dev/pandas...   
3   https://api.github.com/repos/pandas-dev/pandas...   
4   https://api.github.com/repos/pandas-dev/pandas...   
5   https://api.github.com/repos/pandas-dev/pandas...   
6   https://api.github.com/repos/pandas-dev/pandas...   
7   https://api.github.com/repos/pandas-dev/pandas...   
8   https://api.github.com/repos/pandas-dev/pandas...   
9   https://api.github.com/repos/pand

In [90]:
v.head(10)

url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   
5  https://api.github.com/repos/pandas-dev/pandas...   
6  https://api.github.com/repos/pandas-dev/pandas...   
7  https://api.github.com/repos/pandas-dev/pandas...   
8  https://api.github.com/repos/pandas-dev/pandas...   
9  https://api.github.com/repos/pandas-dev/pandas...   

                                   repository_url  \
0  https://api.github.com/repos/pandas-dev/pandas   
1  https://api.github.com/repos/pandas-dev/pandas   
2  https://api.github.com/repos/pandas-dev/pandas   
3  https://api.github.com/repos/pandas-dev/pandas   
4  https://api.github.com/repos/pandas-dev/pandas   
5  https://api.github.com/repos/pandas-dev/pandas   
6  https://api.github.com/repos/pandas-dev/pandas   
7  https://api.github.com/repos/pandas-dev/pandas   
8  https://api.github.com/repos/pandas-dev/pandas   
9  https://api.github.com/repos/pandas-dev/pandas   

                                          labels_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   
5  https://api.github.com/repos/pandas-dev/pandas...   
6  https://api.github.com/repos/pandas-dev/pandas...   
7  https://api.github.com/repos/pandas-dev/pandas...   
8  https://api.github.com/repos/pandas-dev/pandas...   
9  https://api.github.com/repos/pandas-dev/pandas...   

                                        comments_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   
5  https://api.github.com/repos/pandas-dev/pandas...   
6  https://api.github.com/repos/pandas-dev/pandas...   
7  https://api.github.com/repos/pandas-dev/pandas...   
8  https://api.github.com/repos/pandas-dev/pandas...   
9  https://api.github.com/repos/pandas-dev/pandas...   

                                          events_url  \
0  https://api.github.com/repos/pandas-dev/pandas...   
1  https://api.github.com/repos/pandas-dev/pandas...   
2  https://api.github.com/repos/pandas-dev/pandas...   
3  https://api.github.com/repos/pandas-dev/pandas...   
4  https://api.github.com/repos/pandas-dev/pandas...   
5  https://api.github.com/repos/pandas-dev/pandas...   
6  https://api.github.com/repos/pandas-dev/pandas...   
7  https://api.github.com/repos/pandas-dev/pandas...   
8  https://api.github.com/repos/pandas-dev/pandas...   
9  https://api.github.com/repos/pandas-dev/pandas...   

                                            html_url         id  \
0  https://github.com/pandas-dev/pandas/issues/34320  623395066   
1  https://github.com/pandas-dev/pandas/issues/34319  623378523   
2  https://github.com/pandas-dev/pandas/issues/34318  623329370   
3    https://github.com/pandas-dev/pandas/pull/34317  623292601   
4  https://github.com/pandas-dev/pandas/issues/34316  623277600   
5  https://github.com/pandas-dev/pandas/issues/34315  623251023   
6  https://github.com/pandas-dev/pandas/issues/34314  623240428   
7  https://github.com/pandas-dev/pandas/issues/34313  623238977   
8    https://github.com/pandas-dev/pandas/pull/34312  623221272   
9  https://github.com/pandas-dev/pandas/issues/34311  623205893   

                            node_id  number  \
0          MDU6SXNzdWU2MjMzOTUwNjY=   34320   
1          MDU6SXNzdWU2MjMzNzg1MjM=   34319   
2          MDU6SXNzdWU2MjMzMjkzNzA=   34318   
3  MDExOlB1bGxSZXF1ZXN0NDIxOTg4NTkw   34317   
4          MDU6SXNzdWU2M

In [108]:
from numpy.random import rand as rn
np.random.seed(100)#give same number of random data
r=rn(5,4)

In [111]:
pd.DataFrame(r)

0         1         2         3
0  0.543405  0.278369  0.424518  0.844776
1  0.004719  0.121569  0.670749  0.825853
2  0.136707  0.575093  0.891322  0.209202
3  0.185328  0.108377  0.219697  0.978624
4  0.811683  0.171941  0.816225  0.274074

In [112]:
row=['A','B','C','D','E']
col=['W','X','Y','Z']
df=pd.DataFrame(r,index=row,columns=col)
df

W         X         Y         Z
A  0.543405  0.278369  0.424518  0.844776
B  0.004719  0.121569  0.670749  0.825853
C  0.136707  0.575093  0.891322  0.209202
D  0.185328  0.108377  0.219697  0.978624
E  0.811683  0.171941  0.816225  0.274074

In [114]:
df['W']

A    0.543405
B    0.004719
C    0.136707
D    0.185328
E    0.811683
Name: W, dtype: float64

In [117]:
df['new']=df['W']+df['Z']
df

W         X         Y         Z       new
A  0.543405  0.278369  0.424518  0.844776  1.388181
B  0.004719  0.121569  0.670749  0.825853  0.830572
C  0.136707  0.575093  0.891322  0.209202  0.345909
D  0.185328  0.108377  0.219697  0.978624  1.163952
E  0.811683  0.171941  0.816225  0.274074  1.085757

In [123]:
# drop only for rows,if u want to drop column change axis=1
#because default axis=0 it refers to rows.
df.drop['W']

TypeError: 'method' object is not subscriptable

In [128]:
df=df.drop('A')
df

W         X         Y         Z       new
B  0.004719  0.121569  0.670749  0.825853  0.830572
C  0.136707  0.575093  0.891322  0.209202  0.345909
D  0.185328  0.108377  0.219697  0.978624  1.163952
E  0.811683  0.171941  0.816225  0.274074  1.085757

In [129]:
df=df.drop('W',axis=1)

In [130]:
df

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909
D  0.108377  0.219697  0.978624  1.163952
E  0.171941  0.816225  0.274074  1.085757

In [131]:
df.loc['C']

X      0.575093
Y      0.891322
Z      0.209202
new    0.345909
Name: C, dtype: float64

In [133]:
df.loc[['C','B']]

X         Y         Z       new
C  0.575093  0.891322  0.209202  0.345909
B  0.121569  0.670749  0.825853  0.830572

In [136]:
#loc gives the indexes which we named
#iloc gives the original index
df.iloc[1]

X      0.575093
Y      0.891322
Z      0.209202
new    0.345909
Name: C, dtype: float64

In [137]:
df.iloc[['0','1']]

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909

In [138]:
df.loc[['B','C'],['Y']]
#first rowvalues then colun value

Y
B  0.670749
C  0.891322

In [140]:
df.iloc[0:2,:]

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909

In [141]:
df.iloc[0:2,1:3]

Y         Z
B  0.670749  0.825853
C  0.891322  0.209202

In [142]:
df.iloc[::-1,::-1]

new         Z         Y         X
E  1.085757  0.274074  0.816225  0.171941
D  1.163952  0.978624  0.219697  0.108377
C  0.345909  0.209202  0.891322  0.575093
B  0.830572  0.825853  0.670749  0.121569

In [143]:
df.iloc[[0,1]]

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909

In [144]:
df


X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909
D  0.108377  0.219697  0.978624  1.163952
E  0.171941  0.816225  0.274074  1.085757

In [146]:
df[df['X']<1]

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909
D  0.108377  0.219697  0.978624  1.163952
E  0.171941  0.816225  0.274074  1.085757

In [147]:
df[(df['X']>0) & (df['Y']>0)]

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909
D  0.108377  0.219697  0.978624  1.163952
E  0.171941  0.816225  0.274074  1.085757

In [149]:
df.reset_index()

index         X         Y         Z       new
0     B  0.121569  0.670749  0.825853  0.830572
1     C  0.575093  0.891322  0.209202  0.345909
2     D  0.108377  0.219697  0.978624  1.163952
3     E  0.171941  0.816225  0.274074  1.085757

In [153]:
df.reset_index(drop=True)
#inplace =true means it will reflect in our original data

X         Y         Z       new
0  0.121569  0.670749  0.825853  0.830572
1  0.575093  0.891322  0.209202  0.345909
2  0.108377  0.219697  0.978624  1.163952
3  0.171941  0.816225  0.274074  1.085757

In [154]:
df

X         Y         Z       new
B  0.121569  0.670749  0.825853  0.830572
C  0.575093  0.891322  0.209202  0.345909
D  0.108377  0.219697  0.978624  1.163952
E  0.171941  0.816225  0.274074  1.085757

In [155]:
df.reset_index(drop=True,inplace=True)

In [156]:
df

X         Y         Z       new
0  0.121569  0.670749  0.825853  0.830572
1  0.575093  0.891322  0.209202  0.345909
2  0.108377  0.219697  0.978624  1.163952
3  0.171941  0.816225  0.274074  1.085757

In [157]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [159]:
l='sudh devi kumar aru'
df['n']=l.split()
df

X         Y         Z       new      n
0  0.121569  0.670749  0.825853  0.830572   sudh
1  0.575093  0.891322  0.209202  0.345909   devi
2  0.108377  0.219697  0.978624  1.163952  kumar
3  0.171941  0.816225  0.274074  1.085757    aru

In [163]:
df1=pd.DataFrame({'A':[1,2,3],'B':[a,b,c],'C':[np.nan,np.nan,np.nan]})
df1

A                 B   C
0  1            [1, 2] NaN
1  2            [3, 4] NaN
2  3  [(1, 3), (2, 4)] NaN

In [172]:
df1.dropna(axis=1,thresh=3)#axis=1 becuse we want to drop all
# column value.

A                 B
0  1            [1, 2]
1  2            [3, 4]
2  3  [(1, 3), (2, 4)]

In [174]:
df1.fillna(1)

A                 B    C
0  1            [1, 2]  1.0
1  2            [3, 4]  1.0
2  3  [(1, 3), (2, 4)]  1.0

In [180]:
df1.fillna(df1['A'].max)

A                 B                                                  C
0  1            [1, 2]  <bound method Series.max of 0    1\n1    2\n2 ...
1  2            [3, 4]  <bound method Series.max of 0    1\n1    2\n2 ...
2  3  [(1, 3), (2, 4)]  <bound method Series.max of 0    1\n1    2\n2 ...

In [181]:
d=({'name':['a','b','c','d'],
   'income':[100,200,300,400],
   'com':['ineu','amaz','ccc','fff']})

In [182]:
d

{'name': ['a', 'b', 'c', 'd'],
 'income': [100, 200, 300, 400],
 'com': ['ineu', 'amaz', 'ccc', 'fff']}

In [185]:
df2=pd.DataFrame(d)
df2

name  income   com
0    a     100  ineu
1    b     200  amaz
2    c     300   ccc
3    d     400   fff

In [186]:
df2.groupby('name').mean()

income
name        
a        100
b        200
c        300
d        400

In [188]:
df2.groupby('name').sum()

income
name        
a        100
b        200
c        300
d        400

In [203]:
df4=df2.groupby('name').describe()
df4

income                                              
      count   mean std    min    25%    50%    75%    max
name                                                     
a       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0
b       1.0  200.0 NaN  200.0  200.0  200.0  200.0  200.0
c       1.0  300.0 NaN  300.0  300.0  300.0  300.0  300.0
d       1.0  400.0 NaN  400.0  400.0  400.0  400.0  400.0

In [199]:
df3=df2.loc[1]

In [200]:
df4

income                                              
      count   mean std    min    25%    50%    75%    max
name                                                     
a       1.0  100.0 NaN  100.0  100.0  100.0  100.0  100.0
b       1.0  200.0 NaN  200.0  200.0  200.0  200.0  200.0
c       1.0  300.0 NaN  300.0  300.0  300.0  300.0  300.0
d       1.0  400.0 NaN  400.0  400.0  400.0  400.0  400.0

In [206]:
df4['income']

count   mean  std    min    25%    50%    75%    max
name                                                      
a       1.0  100.0  NaN  100.0  100.0  100.0  100.0  100.0
b       1.0  200.0  NaN  200.0  200.0  200.0  200.0  200.0
c       1.0  300.0  NaN  300.0  300.0  300.0  300.0  300.0
d       1.0  400.0  NaN  400.0  400.0  400.0  400.0  400.0

In [208]:
df4['income']['count']

name
a    1.0
b    1.0
c    1.0
d    1.0
Name: count, dtype: float64

In [210]:
df5=df4.T
df5

name              a      b      c      d
income count    1.0    1.0    1.0    1.0
       mean   100.0  200.0  300.0  400.0
       std      NaN    NaN    NaN    NaN
       min    100.0  200.0  300.0  400.0
       25%    100.0  200.0  300.0  400.0
       50%    100.0  200.0  300.0  400.0
       75%    100.0  200.0  300.0  400.0
       max    100.0  200.0  300.0  400.0

In [218]:
d=pd.DataFrame({
    'A':[2,3,4,5],
    'B':[3,4,5,6],
    'C':[4,5,6,7]},
    index=[0,1,2,3])

In [219]:

d1=pd.DataFrame({
    'A':[2,3,4,5],
    'B':[3,4,5,6],
    'C':[4,5,6,7]},
    index=[4,5,6,7])

In [221]:
pd.concat([d,d1])

A  B  C
0  2  3  4
1  3  4  5
2  4  5  6
3  5  6  7
4  2  3  4
5  3  4  5
6  4  5  6
7  5  6  7

In [222]:
d3=pd.concat([d,d1],axis=1)
d3
#if we want to avoid the nan value keep the index value same in both dataframes.

A    B    C    A    B    C
0  2.0  3.0  4.0  NaN  NaN  NaN
1  3.0  4.0  5.0  NaN  NaN  NaN
2  4.0  5.0  6.0  NaN  NaN  NaN
3  5.0  6.0  7.0  NaN  NaN  NaN
4  NaN  NaN  NaN  2.0  3.0  4.0
5  NaN  NaN  NaN  3.0  4.0  5.0
6  NaN  NaN  NaN  4.0  5.0  6.0
7  NaN  NaN  NaN  5.0  6.0  7.0

In [223]:
d4=pd.concat([d,d1],axis=0)
d4

A  B  C
0  2  3  4
1  3  4  5
2  4  5  6
3  5  6  7
4  2  3  4
5  3  4  5
6  4  5  6
7  5  6  7

In [224]:
df.iloc[:,[0]]#all rows and 1 column

X
0  0.121569
1  0.575093
2  0.108377
3  0.171941

In [229]:
l=pd.DataFrame({'k1':['k0','k2','k3','k4'],
               'x':[1,2,3,4],
               'y':[4,5,6,6]})
l

k1  x  y
0  k0  1  4
1  k2  2  5
2  k3  3  6
3  k4  4  6

In [230]:
m=pd.DataFrame({'k1':['k0','k1','k2','k3'],
               'x':[1,2,3,4],
               'y':[4,5,6,6]})
m

k1  x  y
0  k0  1  4
1  k1  2  5
2  k2  3  6
3  k3  4  6

In [231]:
pd.merge(l,m)
# default inner join

k1  x  y
0  k0  1  4

In [232]:
pd.merge(l,m,how='left')

k1  x  y
0  k0  1  4
1  k2  2  5
2  k3  3  6
3  k4  4  6

In [233]:
pd.merge(l,m,how='right')

k1  x  y
0  k0  1  4
1  k1  2  5
2  k2  3  6
3  k3  4  6

In [234]:
pd.merge(l,m,how='left',on='k1')

k1  x_x  y_x  x_y  y_y
0  k0    1    4  1.0  4.0
1  k2    2    5  3.0  6.0
2  k3    3    6  4.0  6.0
3  k4    4    6  NaN  NaN

In [235]:
pd.merge(l,m,how='left',left_on='x',right_on='y')

k1_x  x_x  y_x k1_y  x_y  y_y
0   k0    1    4  NaN  NaN  NaN
1   k2    2    5  NaN  NaN  NaN
2   k3    3    6  NaN  NaN  NaN
3   k4    4    6   k0  1.0  4.0

In [237]:
#merge=depends on column name
#join=depends on index
l.join(m)

ValueError: columns overlap but no suffix specified: Index(['k1', 'x', 'y'], dtype='object')

In [1]:
import numpy as np
a=[3,4,5,6]
np.array(a)

array([3, 4, 5, 6])

In [9]:
v=np.array([[1,2,3],[3,4,5]])
v

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
v[1,0]

3

In [12]:
v.shape

(2, 3)

In [14]:
np.array(([1,2,3]),ndmin=2)

array([[1, 2, 3]])

In [15]:
np.array(([1,2,3]),ndmin=20)

array([[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]])

In [16]:
np.array(([1,2,3]),dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
n=np.array([[3,4],[5,6]],dtype=[('a','<i4'),('b','<i2')])

In [22]:
n

array([[(3, 3), (4, 4)],
       [(5, 5), (6, 6)]], dtype=[('a', '<i4'), ('b', '>i2')])

In [23]:
n[0,0]

(3, 3)

In [32]:
type(n[0][1])

numpy.void

In [36]:
m=np.mat([1,2,34])
m

matrix([[ 1,  2, 34]])

In [34]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [37]:
np.asanyarray(m)

matrix([[ 1,  2, 34]])

In [39]:
#deep copy and shallow copy
a=[1,2,3]
b=[2,3,4]
b=a
b

[1, 2, 3]

In [40]:
b[0]=2
b

[2, 2, 3]

In [41]:
a

[2, 2, 3]

In [42]:
c=np.copy(a)
c

array([2, 2, 3])

In [43]:
c[0]=3
c

array([3, 2, 3])

In [44]:
a#copy-deep copy;b=a shallow copy

[2, 2, 3]

In [45]:
np.fromfunction(lambda x,y : x==y,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [55]:
def a(a,b):
    c=a+b
    return int(c)

In [56]:
np.fromfunction(int(a(2,3)),(0,0))

TypeError: 'int' object is not callable

In [59]:
np.fromstring('1,3',sep=',')

array([1., 3.])

In [68]:
n=np.array([1,2])
n


array([1, 2])

In [69]:
n.ndim

1

In [71]:
n=np.array([[1,2],[2,3]])
n

array([[1, 2],
       [2, 3]])

In [72]:
n.ndim

2

In [73]:
n.size

4

In [74]:
n.shape

(2, 2)

In [105]:
n=np.array([[[1,2,3],[2,3,3]]])
n

array([[[1, 2, 3],
        [2, 3, 3]]])

In [106]:
n.ndim

3

In [155]:
n.shape

(2, 2)

In [108]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [75]:
range(1,2)#only for integer range

range(1, 2)

In [79]:
np.arange(2.5,5.5,0.5)#for floating nnumber

array([2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [80]:
np.arange(2.5,5.5)

array([2.5, 3.5, 4.5])

In [81]:
np.arange(2.5,3)

array([2.5])

In [86]:
np.linspace(3,5,10,endpoint=False)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [87]:
np.linspace(3,5,10,endpoint=True)

array([3.        , 3.22222222, 3.44444444, 3.66666667, 3.88888889,
       4.11111111, 4.33333333, 4.55555556, 4.77777778, 5.        ])

In [88]:
np.linspace(3,5,10,endpoint=False,retstep=True)

(array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8]), 0.2)

In [89]:
np.linspace(3,5,10,endpoint=False,retstep=False)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [90]:
np.linspace(3,5,10,endpoint=False,retstep=True)

(array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8]), 0.2)

In [110]:
np.empty((4,5))#random numbers close to zero 

array([[1.29441743e-312, 2.37663529e-312, 2.05833592e-312,
        2.41907520e-312, 2.56761491e-312],
       [1.93101617e-312, 1.03977794e-312, 1.06099790e-312,
        1.08221785e-312, 9.33678148e-313],
       [1.06099790e-312, 1.08221785e-312, 1.08221785e-312,
        1.97345609e-312, 1.93101617e-312],
       [9.33678148e-313, 9.33678148e-313, 1.97345609e-312,
        8.13373141e-144, 1.50008929e+248]])

In [112]:
np.eye(4,2)#identity matrix

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [113]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [116]:
np.logspace(5.6,7.8,3,base=3)

array([ 469.76323692, 1572.9409051 , 5266.78738671])

In [123]:
m=np.random.rand(4,5)
m

array([[0.90338507, 0.32050625, 0.49888246, 0.72934173, 0.93990977],
       [0.86366872, 0.07106937, 0.91455434, 0.70659152, 0.65386542],
       [0.55114603, 0.08844778, 0.70919464, 0.60072167, 0.16098603],
       [0.58963524, 0.43345233, 0.88873839, 0.01264059, 0.01790667]])

In [124]:
m.shape

(4, 5)

In [125]:
m.reshape(5,4)

array([[0.90338507, 0.32050625, 0.49888246, 0.72934173],
       [0.93990977, 0.86366872, 0.07106937, 0.91455434],
       [0.70659152, 0.65386542, 0.55114603, 0.08844778],
       [0.70919464, 0.60072167, 0.16098603, 0.58963524],
       [0.43345233, 0.88873839, 0.01264059, 0.01790667]])

In [127]:
m.reshape(2,10)

array([[0.90338507, 0.32050625, 0.49888246, 0.72934173, 0.93990977,
        0.86366872, 0.07106937, 0.91455434, 0.70659152, 0.65386542],
       [0.55114603, 0.08844778, 0.70919464, 0.60072167, 0.16098603,
        0.58963524, 0.43345233, 0.88873839, 0.01264059, 0.01790667]])

In [119]:
np.seed(1,2)

AttributeError: module 'numpy' has no attribute 'seed'

In [129]:
np.random.randint(3,7)

6

In [130]:
np.random.randint(3,7,(1,3))

array([[3, 5, 4]])

In [134]:
m=np.array([[0,1],[2,3]])
n=np.array([[2,3],[1,8]])

In [135]:
m*n#normal array multiplication

array([[ 0,  3],
       [ 2, 24]])

In [136]:
m@n#original matrix multiplication result

array([[ 1,  8],
       [ 7, 30]])

In [137]:
m+2

array([[2, 3],
       [4, 5]])

In [150]:
m1=np.random.rand(5,4).reshape(10,2)

In [151]:
m1

array([[0.34069885, 0.9681365 ],
       [0.56284501, 0.42486565],
       [0.21252164, 0.66521433],
       [0.39908777, 0.39690431],
       [0.46392788, 0.88747134],
       [0.18543366, 0.72651669],
       [0.12112557, 0.1857737 ],
       [0.87937251, 0.15710146],
       [0.94453652, 0.14058477],
       [0.21935279, 0.53147924]])

In [152]:
np.sqrt(m1)

array([[0.58369414, 0.98393928],
       [0.75022997, 0.65181719],
       [0.46100069, 0.81560673],
       [0.63173394, 0.63000342],
       [0.68112252, 0.94205697],
       [0.43062008, 0.85235948],
       [0.34803098, 0.43101473],
       [0.93774864, 0.39636026],
       [0.97187269, 0.37494636],
       [0.46835114, 0.72902623]])

In [153]:
np.exp(m1)

array([[1.40592978, 2.63303322],
       [1.75566027, 1.52938494],
       [1.23679287, 1.94490733],
       [1.49046442, 1.48721361],
       [1.59030828, 2.42897982],
       [1.20374034, 2.06786503],
       [1.12876664, 1.20414973],
       [2.40938737, 1.17011433],
       [2.57162121, 1.15094665],
       [1.24527052, 1.70144729]])

In [154]:
np.log(m1)

array([[-1.07675634, -0.03238219],
       [-0.57475099, -0.85598227],
       [-1.54871147, -0.40764599],
       [-0.91857392, -0.92406006],
       [-0.76802616, -0.11937905],
       [-1.6850581 , -0.31949382],
       [-2.11092753, -1.68322603],
       [-0.12854668, -1.85086345],
       [-0.05706093, -1.9619446 ],
       [-1.51707393, -0.63209114]])

In [ ]:
np.fmod(m,m1)